# @package _global_
# Config for taba/scripts/invert_forward/run_ldm_invert_forward.py
defaults:
  - _self_

hydra:
  output_subdir: null
  run:
    dir: .
  job:
    chdir: false

num_inference_steps: 100
input_image_path: null
with_reconstruction: false
seed: 42
batch_size: 64
internal: false
forward_before_t: null
forward_seed: 42
save_dir: null
